# --- ЗОНА ЛИМИТОВ (ЩИТЫ) ---
limit_req_zone $binary_remote_addr zone=mukti_limit:10m rate=10r/s;

server {
    server_name mukti.pro www.mukti.pro;

    location / {
        # --- АКТИВАЦИЯ БРОНИ ---
        limit_req zone=mukti_limit burst=20 nodelay;

        proxy_pass http://127.0.0.1:8501;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mukti.pro/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mukti.pro/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

# --- БЛОК РЕДИРЕКТА (Восстановлен) ---
server {
    if ($host = www.mukti.pro) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    if ($host = mukti.pro) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name mukti.pro www.mukti.pro;
    return 404; # managed by Certbot
}
